### ISSUE TITLE
Problems with reproduction

### ISSUE THREAD

**Issue by Damon9420** [ielab/CharacterBERT-DR#3] opened 2023-09-29 06:30 UTC
Hello author, when I tried to reproduce your code, the system returned the following error message. I configured the same environment as you requested, and since I couldn't load the dataset and model from huggingface, I saved them locally, which I don't think will affect the reproduction much.
![46103d0c30ecfa796f61c3d961225fa](https://github.com/ielab/CharacterBERT-DR/assets/111229358/16c1932f-5f42-4417-bc09-01d6da08d6a0)

**Comment by ArvinZhuang** [comment] 2023-09-29 06:41
Hi, @Damon9420 Thanks for raising this issue.
 
maybe just try add `_keys_to_ignore_on_save = None` to `DistilTypoDenseModel` here?https://github.com/ielab/CharacterBERT-DR/blob/92f08aa13c64eb46675ecfb89c5487f4cec7b866/src/tevatron/modeling.py#L286

I feel it is just transformers version problem, are you using transformers==4.9.2?

**Comment by Damon9420** [comment] 2023-09-29 07:33
I tried setting this property to None, but the code produced a new error.
![64acf5f900c78561d002ad5f238e0d4](https://github.com/ielab/CharacterBERT-DR/assets/111229358/e67ab074-f37d-45a5-8c91-b5496d36c087)

![9f2bd2999663b54e96c21a918621721](https://github.com/ielab/CharacterBERT-DR/assets/111229358/7d01e948-9784-42b2-8377-ef9d6bfd6a96)

 I did use transformers 4.9.2. 
![ae96b2ec8294d9c34f5f6d9bffc4a0e](https://github.com/ielab/CharacterBERT-DR/assets/111229358/7995eca0-efd0-42c4-8484-a3a7733e98fa)

For your code, I only changed the data name used when the data is loaded.
![b803123044378c55827b33ed54b2e72](https://github.com/ielab/CharacterBERT-DR/assets/111229358/a5044ec7-1df0-4c24-8c90-3ef997ad9b4d)
![83285fcf79a2692f92be35b8485f94d](https://github.com/ielab/CharacterBERT-DR/assets/111229358/4d993a72-aec6-4227-9cc0-b84a281eba1e)

**Comment by ArvinZhuang** [comment] 2023-09-29 07:58
Hi @Damon9420 can you try directly add `_keys_to_ignore_on_save  = None` under line 286? 
do not do `self._keys_to_ignore_on_save = ..`

something like this:
![image](https://github.com/ielab/CharacterBERT-DR/assets/46237844/4194492a-2d7e-4069-a9f4-797c912ad937)

**Comment by Damon9420** [comment] 2023-09-29 12:00
I exactly added '_keys_to_ignore_on_save = None' below line 286. 
![8201b558b7370ca49b4ef04f934df97](https://github.com/ielab/CharacterBERT-DR/assets/111229358/790abd27-b1ae-4160-9e49-41b7f532f188)

After that, the code throws a new error. 
![a894f5e00d5c92423b8b8052921e51e](https://github.com/ielab/CharacterBERT-DR/assets/111229358/6ec41718-21b4-477f-9057-0ecb96f6ba45)

I assume you mean you need to save all the keys, but doing so will also throw another error. Because in train.py it just compares whether 'load_result.missing_keys' is equal to' self.model._keys_to_ignore_on_save '.
![8b2133008d2abf3c0e6a102e8f4bb21](https://github.com/ielab/CharacterBERT-DR/assets/111229358/97892c56-758f-49b8-9329-ef4b9be75bc9)

**Comment by Damon9420** [comment] 2023-09-29 12:06
When I set this property to empty, 
![9aa84b18251f173acad8ef95a690d01](https://github.com/ielab/CharacterBERT-DR/assets/111229358/2ed7780e-8f19-4e47-ab96-7bb3ce3573a2)

I get the following error
![cfde6d84797c5d32d9ff26666e9985d](https://github.com/ielab/CharacterBERT-DR/assets/111229358/4745d822-5407-4b3e-a04a-c8d94076000a)

**Comment by ArvinZhuang** [comment] 2023-09-30 06:25
can you share your command? this looks like related to training data.

or are you using the standard BERT model but set character_query_encoder=True?

**Comment by Damon9420** [comment] 2023-09-30 06:42
Thank you very much for your help, this problem has been solved. I saw that you recently published another paper called ToRoDer, which is quite an excellent paper that brings new ideas to defense models. Finally, I wish you all the best in your scientific research.

**Comment by ArvinZhuang** [comment] 2023-09-30 06:45
Thanks for your kind words :) I'm glad you are interested in our work!

I am closing this issue as the problem is solved

**Closed as completed by ArvinZhuang** 2023-09-30 06:45 UTC
